# Generated by Django 5.1.4 on 2024-12-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0003_alter_animal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('numero', models.CharField(max_length=7)),
                ('esta_limpio', models.BooleanField(null=True)),
                ('zona', models.CharField(choices=[('NORTE', 'NORTE'), ('SUR', 'SUR'), ('ESTE', 'ESTE'), ('OESTE', 'OESTE')], max_length=50, null=True)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jaulas', to='claseZoologico.animal')),
            ],
            options={
                'verbose_name': 'Jaula',
                'verbose_name_plural': 'Jaulas',
            },
        ),
    ]
