# Generated by Django 5.1.4 on 2024-12-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0004_jaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='identificacion',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='numero',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='identificacion',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
