# Generated by Django 5.1.4 on 2024-12-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0005_alter_cuidador_identificacion_alter_jaula_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaula',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(auto_now=True, verbose_name='Fecha de visita')),
                ('numero', models.CharField(editable=False, max_length=7, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claseZoologico.cliente')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
