# Generated by Django 5.1.4 on 2024-12-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0006_alter_jaula_capacidad_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaula',
            name='esta_limpio',
            field=models.BooleanField(null=True, verbose_name='Esta limpio?'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='claseZoologico.boleto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
