# Generated by Django 5.1.4 on 2024-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0009_alter_personallimpieza_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='personallimpieza',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='edad',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
