# Generated by Django 5.1.4 on 2024-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claseZoologico', '0010_animal_edad_cliente_edad_cuidador_edad_guia_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='valor',
            field=models.FloatField(default=2.5, editable=False),
        ),
    ]
